spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=NORTHWIND;encrypt=false
    username: sa
    password: a123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  config:
    activate:
      on-profile: oauth

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8081